# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Gradle Android
      uses: Raul6469/android-gradle-action@2.0.0
      with:
        # The gradle command you wish to run (required)
        # Here, `./gradlew test` will be run
        script: build
