package com.bitmovin.analytics.config

data class SourceMetadata(
    val title: String? = null,
    val videoId: String? = null,
    val cdnProvider: String? = null,
    var experimentName: String? = null,
    val mpdUrl: String? = null,
    val m3u8Url: String? = null,
    val path: String? = null,
    val isLive: Boolean? = null,
    var customData1: String? = null,
    var customData2: String? = null,
    var customData3: String? = null,
    var customData4: String? = null,
    var customData5: String? = null,
    var customData6: String? = null,
    var customData7: String? = null,
    var customData8: String? = null,
    var customData9: String? = null,
    var customData10: String? = null,
    var customData11: String? = null,
    var customData12: String? = null,
    var customData13: String? = null,
    var customData14: String? = null,
    var customData15: String? = null,
    var customData16: String? = null,
    var customData17: String? = null,
    var customData18: String? = null,
    var customData19: String? = null,
    var customData20: String? = null,
    var customData21: String? = null,
    var customData22: String? = null,
    var customData23: String? = null,
    var customData24: String? = null,
    var customData25: String? = null
)
