version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "collector/build.gradle" }}-{{ checksum  "collector-exoplayer/build.gradle" }}-{{ checksum  "collector-exoplayer-v1/build.gradle" }}-{{ checksum  "collector-bitmovin-player/build.gradle" }}-{{ checksum  "collector-bitmovin-player-v1/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "collector/build.gradle" }}-{{ checksum  "collector-exoplayer/build.gradle" }}-{{ checksum  "collector-exoplayer-v1/build.gradle" }}-{{ checksum  "collector-bitmovin-player/build.gradle" }}-{{ checksum  "collector-bitmovin-player-v1/build.gradle" }}
      - run:
          name: Code style spotlessCheck
          command: ./gradlew spotlessCheck
      - run:
          name: Run Lint and Tests
          command: ./gradlew lint test
      - run:
          name: SonarQube
          command: ./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: collector/build/reports
          destination: reports
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: collector-bitmovin-player/build/reports
          destination: reports
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: collector-bitmovin-player-v1/build/reports
          destination: reports
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: collector-exoplayer/build/reports
          destination: reports
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: collector-exoplayer-v1/build/reports
          destination: reports
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: collector/build/test-results
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: collector-bitmovin-player/build/test-results
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: collector-bitmovin-player-v1/build/test-results
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: collector-exoplayer/build/test-results
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: collector-exoplayer-v1/build/test-results

workflows:
  version: 2
  android-build:
    jobs:
      - build:
          context:
            - analytics
            - SonarCloud
