version: 2
jobs:
  build:
    working_directory: ~/code
    resource_class: large
    docker:
      - image: cimg/android:2023.12.1
    environment:
      # https://support.circleci.com/hc/en-us/articles/360021812453-Common-Android-memory-issues
      _JAVA_OPTIONS: -Xmx3g
      GRADLE_OPTS: -Dkotlin.compiler.execution.strategy=in-process
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "collector/build.gradle" }}-{{ checksum  "collector-exoplayer/build.gradle" }}-{{ checksum  "collector-bitmovin-player/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies --no-daemon --max-workers=2 #https://support.circleci.com/hc/en-us/articles/360021812453-Common-Android-memory-issues
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "collector/build.gradle" }}-{{ checksum  "collector-exoplayer/build.gradle" }}-{{ checksum  "collector-bitmovin-player/build.gradle" }}
      - run:
          name: Code style spotlessCheck
          command: ./gradlew spotlessCheck --no-daemon --max-workers=2 #https://support.circleci.com/hc/en-us/articles/360021812453-Common-Android-memory-issues
      - run:
          name: Run Lint
          command: ./gradlew lint --no-daemon --max-workers=2 #https://support.circleci.com/hc/en-us/articles/360021812453-Common-Android-memory-issues
      - run:
          name: Run Tests
          command: ./gradlew test --no-daemon --max-workers=2 #https://support.circleci.com/hc/en-us/articles/360021812453-Common-Android-memory-issues
      - run:
          name: SonarQube
          command: ./gradlew --no-daemon --max-workers=2 sonarqube -Dsonar.login=$SONAR_TOKEN #https://support.circleci.com/hc/en-us/articles/360021812453-Common-Android-memory-issues
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: collector/build/reports
          destination: reports
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: collector-bitmovin-player/build/reports
          destination: reports
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: collector-exoplayer/build/reports
          destination: reports
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: collector-amazon-ivs/build/reports
          destination: reports
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: collector/build/test-results
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: collector-bitmovin-player/build/test-results
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: collector-exoplayer/build/test-results
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: collector-amazon-ivs/build/test-results

workflows:
  version: 2
  android-build:
    jobs:
      - build:
          context:
            - analytics
            - SonarCloud
