#!/bin/bash

# This script connects every reports generated by the SystemTests.yml (on Remote GitHub Actions) to a unified index.html file.
# This is necessary because to avoid a wasting time to open every report when there is a failure in the tests.

# Guarding against missing DIR (first) argument.
if [ -z "$1" ]; then
  echo "Usage: $0 file_path"
  exit 1
fi

DIR=$1

# Check if the directory exists
if [ ! -d "$DIR" ]; then
  echo "Directory $DIR does not exist."
  exit 1
fi

# Iterate over all files in the directory and its subdirectories
find "$DIR" -type f | while read -r FILE; do
  # Skip these two files:
  # First is to avoid the script to break itself if for some reason he happens to be in the same directory as the reports.
  # Second is to avoid the script to break the hardcoded index.html file.
  if [ "$FILE" == "$DIR/report_enhancer.sh" ] || [ "$FILE" == "$DIR/index.html" ]; then
    continue
  fi

  # Verify if the file is a text file
  if file "$FILE" | grep -q text; then
    # Replace "index.html" with "../index.html" in all text files to connect the reports to the main index.html and not their own one.
    sed -i 's#"index.html"#"../index.html"#g' "$FILE"
  fi
done