package com.bitmovin.analytics.dtos

import kotlinx.serialization.Serializable

@Serializable
enum class HttpRequestType(val value: String) {
    DRM_LICENSE_WIDEVINE("DRM_LICENSE_WIDEVINE"),
    DRM_OTHER("DRM_OTHER"),
    MEDIA_THUMBNAILS("MEDIA_THUMBNAILS"),
    MEDIA_VIDEO("MEDIA_VIDEO"),
    MEDIA_AUDIO("MEDIA_AUDIO"),
    MEDIA_PROGRESSIVE("MEDIA_PROGRESSIVE"),
    MEDIA_SUBTITLES("MEDIA_SUBTITLES"),
    MANIFEST_DASH("MANIFEST_DASH"),
    MANIFEST_HLS("MANIFEST_HLS"),
    MANIFEST_HLS_MASTER("MANIFEST_HLS_MASTER"),
    MANIFEST_HLS_VARIANT("MANIFEST_HLS_VARIANT"),
    MANIFEST_SMOOTH("MANIFEST_SMOOTH"),
    MANIFEST("MANIFEST"),
    KEY_HLS_AES("KEY_HLS_AES"),
    UNKNOWN("UNKNOWN"),
}
