#!/bin/sh
# From gist at https://gist.github.com/chadmaughan/5889802

echo '[git hook] executing gradle spotlessCheck before commit'

# stash any unstaged changes
git stash -q --keep-index --include-untracked
STASH_RESULT=$?

# run the spotlessCheck with the gradle wrapper
./gradlew spotlessCheck --daemon

# store the last exit code in a variable
RESULT=$?

# unstash the unstashed changes
if [ $STASH_RESULT -e 0 ];
then git stash pop -q;
fi

# return the './gradlew spotlessCheck' exit code
exit $RESULT
